### ISSUE TITLE
FileNotFoundError: Could not find module 'C:\Users\...\lib\site-packages\treelite\lib\treelite.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by RNarayan73** [dmlc/treelite#439] opened 2023-02-08 18:23 UTC
Hello,
Having installed treelite from conda-forge, I get the error:

> FileNotFoundError: Could not find module 'C:\Users\...\lib\site-packages\treelite\lib\treelite.dll' (or one of its dependencies). Try using the full path with constructor syntax.

when trying to import treelite. When I checked the folder, the file itself does exist.

I'd appreciate any suggestions to resolve this.

Thanks
Narayan

**Comment by hcho3** [comment] 2023-02-22 05:30
I just tried importing Treelite on my Windows machine, and I am not able to reproduce the error.

Do you have any space in the name of your home directory?

**Comment by hcho3** [comment] 2023-02-22 05:39
Just tried setting a new Conda env in a path containing space. It still works fine for me.

```
In [1]: import treelite

In [3]: treelite.core._LIB
Out[3]: <CDLL 'C:\Users\foo bar\foobar\lib\site-packages\treelite\lib\treelite.dll', handle 7ffb8a960000 at 0x25d85add6f0>
```

**Comment by hcho3** [comment] 2023-02-22 05:40
Going to close this for now. You should try re-installing Conda and setting up a new Conda environment from scratch.

**Closed as completed by hcho3** 2023-02-22 05:40 UTC
