### ISSUE TITLE
[FEA] Provide serialization format with forward-compatibility guarantee

### ISSUE THREAD

**Issue by wphicks** [dmlc/treelite#391] opened 2022-08-10 14:33 UTC
It would be useful to have a Treelite serialization format that is guaranteed to work with future versions of Treelite within a major version.

**Comment by hcho3** [comment] 2022-08-19 23:34
I'll prioritize this for the next release of Treelite.

**Comment by hcho3** [comment] 2022-08-20 01:10
# Proposal for updated serialization format

This proposal aims to update the existing serialization format to provide for forward compatibility within the 3.x major version, while maintaining adequate performance.

New fields will be added to the current model spec as follows (**bolded** indicates new fields):

* Header
  * Major version
  * Minor version
  * Patch version
  * Threshold type
  * Leaf output type
* **Number of trees**
* Header 2
  * Number of features in data
  * Task type (regression, classification etc)
  * Whether to average tree outputs
  * Task parameters (`TaskParam`)
  * Model parameters (pred_transform, sigmoid_alpha, ratio_c, global_bias)
* **Extension slot 1: Per-model optional fields**
  - **Number of fields**
  - **Field 1**
  - **Field 2**
  - **...**
* Trees
  - Number of nodes
  - If categorical splits exist
  - Array of nodes
  - Leaf vectors
     - Content (`leaf_vector_`)
     - Beginning offset of each segment (`leaf_vector_begin_`)
     - Ending offset of each segment (`leaf_vector_end_`)
  - Matching categories (for categorical splits)
     - Content (`matching_categories_`)
     - Beginning offset of each segment (`matching_categories_offset_`)
  - **Extension slot 2: Per-tree optional fields**
     - **Number of fields**
     - **Field 1**
     - **Field 2**
     - **...**
  - **Extension slot 3: Per-node optional fields**
     - **Number of fields**
     - **Field 1**
     - **Field 2**
     - **...**

Extension slots will be marked as explicitly empty if empty.

**Rationale**.
* The extension slots were chosen judiciously to avoid enlarging important structures such as `ModelParam`, `TaskParam`, and `Node`. In particular, enlarging `Node` would result into a significant performance loss (#323).
* The slots may have multiple fields, so that future addition of new fields will not break compatibility. Forward compatibility is ensured as long as we only add new fields and never remove them. We need to document the index ID of each field.
* The existing fields are left unmodified, so that we don't have to maintain two separate paths for loading 2.x and 3.x model inputs. The extension slots will correspond to code path wrapped with a version check, like this:
```
if (major_vesion >= 3) {
   // Serialize extra fields ...
}
```
* The current model spec is fairly comprehensive and able to accommodate a large class of tree models in the wild. I do not expect very large changes occurring, other than one-off field additions.

**Comment by hcho3** [comment] 2022-08-30 06:03
**Expected compatibility matrix:**
|             | To: `=2.4`  | To: `=3.0` | To: `>=3.1,<4.0` | To: `>=4.0` |
|-------------|-----------|----------|------------|------------|
| From: `<2.4`  |   :x:     |   :x:  |     :x:   |   :x:   |
| From: `=2.4`  |    :heavy_check_mark:    |    :heavy_check_mark:  |   :heavy_check_mark:     |   :x:   |
| From: `=3.0`  |   :x:    |  :heavy_check_mark:    |   :heavy_check_mark:  |   :heavy_check_mark:   |
| From: `>=3.1,<4.0` |    :x:    |    :heavy_check_mark:    |  :heavy_check_mark:    |  :heavy_check_mark:   |
| From: `>=4.0` |    :x:    |    :x:    |  :x:    |  :heavy_check_mark:   |

**Comment by hcho3** [comment] 2022-08-30 07:27
After more deliberation, I arrived at the following conclusion:
**The in-memory serialization (`GetPyBuffer`) and the checkpoint serialization (`SerializeToFile`) have fundamentally diverging requirements.** So we're better off separating two serialization paths.

* Every PyBuffer frame in the in-memory serialized output must correspond to a concrete address in an in-memory address, so a frame cannot be `num_tree` or `num_field`
* Extension slots in the serialization format means that we will be **re-ordering and packing** some fields prior to serializing to bytes. Re-ordering goes against the purpose of PyBuffer mechanism, namely to transparently expose object representation to the Python layer
* In general, the PyBuffer in-memory serialization is aimed to be zero-overhead and fast. Adding extra info for the sake of compatibility is against this goal.

Decisions:
* **Separate out two serialization methods into two separate code paths**. Currently they share a common code path due to a past attempt at code re-use. Given their diverging requirements and concepts, using the same abstraction is no longer appropriate. Plus, the use of `SerializeTemplate` and `DeserializeTemplate` abstractions make the serialization code harder to grok.
* The in-memory serialization will continue with the current policy: no backward or forward compatibility.
* Checkpoint serialization will support backward and forward compatibility within the major version. See the compatibility matrix above.

Considered alternative: Store `num_tree` or `num_field` physically inside the model object. It makes a brittle codebase, since any code that modifies the model object now need to also update the `num_tree` and `num_field` fields. It's better to compute these values on the fly as part of serialization logic.

**Comment by hcho3** [comment] 2022-08-30 08:48
I decided against having two separate paths, since it would greatly increase the codebase and maintenance burden.

Building a wholly separate logic for checkpoint serializer is supposed to allow greater freedom in re-ordering fields in the object, but for performance reasons we do not want large gap between the internal object and the serialized bytes.

How do we handle `num_tree` and `num_field`? They should be stored as part of the model object. To ensure that these magic numbers and computed correctly, they will be computed fresh when the model's serialization function is called.

We should re-visit once we have the need for faster in-memory serialization.

**Comment by hcho3** [comment] 2022-09-06 23:09
**How to handle extra fields**

In supporting forward compatibility (e.g. save in 3.1 and load in 3.0), we need a good way to handle extra fields in the extension slots. The older version of Treelite should gracefully handle the extra fields by ignoring them; it should not throw an error.

**So every field in the extension slot must be serialized as follows:**
```
[Size of each element in bytes] [Number of elements] [Elements]
```
A scalar field will be expressed as an array of length 1.

By specifying the size and length explicitly, it is easy to fast-forward the file pointer to ignore an extra field.

**Closed as completed** 2022-09-08 17:16 UTC
